DROP TABLE IF EXISTS mahasiswa;
CREATE TABLE mahasiswa (
  "Marital_status" INTEGER,
  "Application_mode" INTEGER,
  "Application_order" INTEGER,
  "Course" INTEGER,
  "Daytime_evening_attendance" INTEGER,
  "Previous_qualification" INTEGER,
  "Previous_qualification_grade" DOUBLE PRECISION,
  "Nacionality" INTEGER,
  "Mothers_qualification" INTEGER,
  "Fathers_qualification" INTEGER,
  "Mothers_occupation" INTEGER,
  "Fathers_occupation" INTEGER,
  "Admission_grade" DOUBLE PRECISION,
  "Displaced" INTEGER,
  "Educational_special_needs" INTEGER,
  "Debtor" INTEGER,
  "Tuition_fees_up_to_date" INTEGER,
  "Gender" INTEGER,
  "Scholarship_holder" INTEGER,
  "Age_at_enrollment" INTEGER,
  "International" INTEGER,
  "Curricular_units_1st_sem_credited" INTEGER,
  "Curricular_units_1st_sem_enrolled" INTEGER,
  "Curricular_units_1st_sem_evaluations" INTEGER,
  "Curricular_units_1st_sem_approved" INTEGER,
  "Curricular_units_1st_sem_grade" DOUBLE PRECISION,
  "Curricular_units_1st_sem_without_evaluations" INTEGER,
  "Curricular_units_2nd_sem_credited" INTEGER,
  "Curricular_units_2nd_sem_enrolled" INTEGER,
  "Curricular_units_2nd_sem_evaluations" INTEGER,
  "Curricular_units_2nd_sem_approved" INTEGER,
  "Curricular_units_2nd_sem_grade" DOUBLE PRECISION,
  "Curricular_units_2nd_sem_without_evaluations" INTEGER,
  "Unemployment_rate" DOUBLE PRECISION,
  "Inflation_rate" DOUBLE PRECISION,
  "GDP" DOUBLE PRECISION,
  "Status" TEXT,
  "rasio_sem1" DOUBLE PRECISION,
  "rasio_sem2" DOUBLE PRECISION,
  "band_sem1" TEXT,
  "band_sem2" TEXT,
  "spp" TEXT,
  "prodi" TEXT,
  "status_spp" TEXT,
  "kelas" TEXT,
  "gender" TEXT,
  "beasiswa" TEXT,
  "debitur" TEXT,
  "pernikahan" TEXT,
  "kelompok_usia" TEXT,
  "sel_progresi" TEXT,
  "arah_progresi" TEXT,
  "kelompok_tersembunyi" TEXT,
  "tahap_funnel" TEXT,
  "is_dropout" INTEGER,
  "risiko_sem1" DOUBLE PRECISION,
  "risiko_sem2" DOUBLE PRECISION,
  "tingkat_risiko" TEXT,
  "pendapatan_berisiko" DOUBLE PRECISION
);
